using System.Globalization;
using Avalonia.Controls;
using Avalonia.Headless.XUnit;
using InterCat.Application;
using InterCat.Desktop;
using InterCat.Desktop.Presentation;
using InterCat.Storage;
using Xunit;

namespace InterCat.Ui.Tests;

/// <summary>
/// M5's generated demo in the window: wherever the window shows one of its sessions - the disclosure under its views, the
/// health strip, the title, the saved sessions list - it says the session was generated, in the words icat uses (R18).
/// </summary>
public sealed class DemoSessionWindowTests
{
    [AvaloniaFact(DisplayName = "R18: a demo session says it was generated wherever the window shows it, in icat's words")]
    public void ADemoSessionSaysItWasGenerated()
    {
        string folder = Path.Combine(Path.GetTempPath(), "intercat-demo-window-" + Guid.NewGuid().ToString("N"));
        var window = new MainWindow { Width = 1_080, Height = 700 };
        try
        {
            DemoInvestigationResult made = DemoInvestigation.Create(folder);
            SessionStore store = SessionStore.OpenExisting(LocalOwnedDirectory.Open(made.ClientSession));
            SessionOverviewBundle overview = SessionOverviewProjector.Project(store);
            store.ReleaseSegmentReaders();
            window.Show();
            window.ApplyCaptureUpdate(new(CaptureUiPhase.Complete, "Saved session open", "Saved.",
                SessionPath: made.ClientSession, Overview: overview), forceOverview: true);
            Avalonia.Threading.Dispatcher.UIThread.RunJobs();

            // The disclosure under its views opens with what icat session notes, and the strip and title name it.
            var workspace = Assert.IsType<WorkspaceViewModel>(window.DataContext);
            Assert.StartsWith(DemoInvestigation.Disclosure + " ", workspace.WorkspaceDisclosure, StringComparison.Ordinal);
            Assert.Equal("Demo session, generated by InterCat", window.GetControl<TextBlock>("HealthStateText").Text);
            Assert.StartsWith("Demo session · generation ", workspace.Title, StringComparison.Ordinal);

            // The saved sessions list names both of its sessions as the demo's, never as a capture.
            IReadOnlyList<RecentSessionRow> rows = RecentSessions.Find(folder, DateTimeOffset.UtcNow, TimeZoneInfo.Utc,
                CultureInfo.InvariantCulture);
            Assert.Equal(["Demo session, generated by InterCat", "Demo session, generated by InterCat"], rows.Select(row => row.Title));

            // Its investigation's window says it first among what it states of its sessions.
            Assert.Equal(DemoInvestigation.Disclosure,
                InvestigationRows.Describe(made.WorkspacePath, CultureInfo.InvariantCulture).Caveats[0]);
        }
        finally
        {
            window.Close();
            if (Directory.Exists(folder)) Directory.Delete(folder, recursive: true);
        }
    }
}
