<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../InterCat.Domain/InterCat.Domain.csproj" />
    <ProjectReference Include="../InterCat.CaptureBroker.Protocol/InterCat.CaptureBroker.Protocol.csproj" />
    <ProjectReference Include="../InterCat.Storage/InterCat.Storage.csproj" />
    <ProjectReference Include="../InterCat.Capture.Windows/InterCat.Capture.Windows.csproj" />
    <ProjectReference Include="../InterCat.Capture.Recording/InterCat.Capture.Recording.csproj" />
  </ItemGroup>
</Project>
