<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InterCat.Domain/InterCat.Domain.csproj" />
    <ProjectReference Include="../../src/InterCat.Storage/InterCat.Storage.csproj" />
  </ItemGroup>
</Project>
