using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using InterCat.Desktop.Theme;

// Writes the theme definition and its measured verification into theme/ (section 21.2 item 9). Goldens are
// regenerated by this explicit command, never as a side effect of running tests (section 13.6).
string outputDirectory = args.Length > 0 ? args[0] : "theme";
Directory.CreateDirectory(outputDirectory);

var options = new JsonSerializerOptions(JsonSerializerDefaults.Web) { WriteIndented = true };
options.Converters.Add(new JsonStringEnumConverter());

var tokens = new
{
    themeVersion = ThemePalette.ThemeVersion,
    order = ThemePalette.Order,
    modes = new[] { ThemeMode.Dark, ThemeMode.Light }.Select(mode => new
    {
        mode = mode.ToString(),
        surfaces = new
        {
            canvas = ThemePalette.Surfaces(mode).Canvas.ToHex(),
            panel = ThemePalette.Surfaces(mode).Panel.ToHex(),
            plot = ThemePalette.Surfaces(mode).Plot.ToHex(),
            elevated = ThemePalette.Surfaces(mode).Elevated.ToHex(),
            accent = ThemePalette.Surfaces(mode).Accent.ToHex(),
            ink = ThemePalette.Surfaces(mode).Ink.ToHex(),
            mutedInk = ThemePalette.Surfaces(mode).MutedInk.ToHex(),
        },
        status = new
        {
            caution = ThemePalette.Status(mode).Caution.ToHex(),
            actionFill = ThemePalette.Status(mode).ActionFill.ToHex(),
            actionFillHover = ThemePalette.Status(mode).ActionFillHover.ToHex(),
            actionFillPressed = ThemePalette.Status(mode).ActionFillPressed.ToHex(),
            actionInk = ThemePalette.Status(mode).ActionInk.ToHex(),
        },
        families = ThemePalette.Families(mode).Select(family => new
        {
            family = family.Family.ToString(),
            family.Label,
            family.Glyph,
            fill = family.Fill.ToHex(),
            ink = family.Ink.ToHex(),
        }),
    }),
};

ThemeReport report = ThemeVerification.Verify(DateTimeOffset.UtcNow);

await File.WriteAllTextAsync(
    Path.Combine(outputDirectory, "tokens.json"),
    JsonSerializer.Serialize(tokens, options)).ConfigureAwait(false);
await File.WriteAllTextAsync(
    Path.Combine(outputDirectory, "contrast-report.json"),
    JsonSerializer.Serialize(report, options)).ConfigureAwait(false);

var summary = new StringBuilder();
summary.AppendLine("# Theme verification");
summary.AppendLine();
summary.AppendLine(CultureInfo.InvariantCulture, $"Theme version {report.ThemeVersion}, generated {report.GeneratedUtc:yyyy-MM-dd}.");
summary.AppendLine();
foreach (string threshold in report.Thresholds)
{
    summary.AppendLine(CultureInfo.InvariantCulture, $"- {threshold}");
}

foreach (ThemeModeReport mode in report.Modes)
{
    summary.AppendLine();
    summary.AppendLine(CultureInfo.InvariantCulture, $"## {mode.Mode}");
    summary.AppendLine();
    summary.AppendLine("| Check | Worst measured | Required | Result |");
    summary.AppendLine("|---|---|---|---|");
    AppendWorstContrast(summary, "Ink contrast", mode.InkContrast);
    AppendWorstContrast(summary, "Fill contrast", mode.FillContrast);
    AppendWorstSeparation(summary, mode.Separations);
    AppendWorstSeparation(summary, mode.StatusSeparations, "Caution from every family");
}

await File.WriteAllTextAsync(Path.Combine(outputDirectory, "README.md"), summary.ToString()).ConfigureAwait(false);

Console.WriteLine(report.Satisfied
    ? $"Theme {report.ThemeVersion} satisfies every recorded threshold."
    : $"Theme {report.ThemeVersion} FAILS at least one threshold; see contrast-report.json.");
return report.Satisfied ? 0 : 1;

static void AppendWorstContrast(StringBuilder builder, string label, IReadOnlyList<ContrastResult> results)
{
    ContrastResult worst = results.OrderBy(result => result.Ratio).First();
    builder.AppendLine(CultureInfo.InvariantCulture,
        $"| {label} | {worst.Ratio:F2} to 1 ({worst.Token} on {worst.Surface}) | {worst.Required:F1} to 1 | {(worst.Satisfied ? "met" : "NOT MET")} |");
}

static void AppendWorstSeparation(StringBuilder builder, IReadOnlyList<SeparationResult> results, string? label = null)
{
    foreach (IGrouping<string, SeparationResult> group in results.GroupBy(result => result.Model))
    {
        SeparationResult worst = group.OrderBy(result => result.Distance).First();
        builder.AppendLine(CultureInfo.InvariantCulture,
            $"| {label ?? "Separation"}, {group.Key} | {worst.Distance:F1} ({worst.First} to {worst.Second}) | {worst.Required:F0} | {(worst.Satisfied ? "met" : "NOT MET")} |");
    }
}
