<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../InterCat.Domain/InterCat.Domain.csproj" />
    <ProjectReference Include="../InterCat.Storage/InterCat.Storage.csproj" />
    <ProjectReference Include="../InterCat.Analysis/InterCat.Analysis.csproj" />
  </ItemGroup>
</Project>
