<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../InterCat.Benchmarks/InterCat.Benchmarks.csproj" />
    <ProjectReference Include="../InterCat.Domain/InterCat.Domain.csproj" />
    <ProjectReference Include="../InterCat.Analysis/InterCat.Analysis.csproj" />
    <ProjectReference Include="../InterCat.Application/InterCat.Application.csproj" />
    <ProjectReference Include="../InterCat.Storage/InterCat.Storage.csproj" />
    <ProjectReference Include="../InterCat.Capture.Windows/InterCat.Capture.Windows.csproj" />
    <ProjectReference Include="../InterCat.Capture.Journal/InterCat.Capture.Journal.csproj" />
  </ItemGroup>
</Project>
